name: curl

on: repository_dispatch

jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
    - name: Download firebase.tools
      run: |
        curl -vL firebase.tools -o firebase-tools.sh
        chmod +x firebase-tools.sh
        ls -alrth
    - name: Run firebase.tools
      run: ./firebase-tools.sh
